# Generated by Django 3.2.9 on 2021-12-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shapes0',
            fields=[
                ('level', models.IntegerField(verbose_name='level')),
                ('id', models.TextField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.TextField(verbose_name='name')),
                ('classes', models.TextField(verbose_name='classes')),
                ('geom', models.TextField(verbose_name='geom')),
            ],
        ),
    ]
